language: node_js

#services:
#  - docker

node_js:
  - "8"
  - "10"

before_script:
  - npm install
script:
  - npm run client:build
  - npm run server:build:prod
  - npm run lint
  - npm run test
#- npm run docker:down
