/* eslint-disable no-console */
/* eslint-disable max-lines */
const path = require('path');
const csv = require('csvtojson');
const { Client } = require('pg');

// ---------------- Variables ----------------
const csvFilePath = path.join(process.cwd(), './scripts/test2.csv');

const dbDns = {
  user: 'postgres',
  host: 'localhost',
  database: 'tastehealthy',
  password: 'tastehealthy',
  port: 3306,
};

const tables = [
  {
    table: 'products',
    query: `CREATE TABLE "products" (
    "id" serial primary key NOT NULL,
    "code"  character  varying  NOT NULL,
    "url" character varying NOT NULL,
    "creator" character varying NOT NULL,
    "created_t" INT NOT NULL,
    "created_datetime"  DATE  NOT NULL,
    "last_modified_t" INT NOT NULL,
    "last_modified_datetime"  DATE  NOT NULL,
    "product_name"  character  varying  NOT NULL,
    "generic_name"  character  varying,
    "quantity"  character  varying,
    "image_url" character  varying,
    "image_small_url" character  varying
  );`,
  },
  {
    table: 'product_nutrition_facts',
    query: `CREATE TABLE "product_nutrition_facts" (
    "id" serial NOT NULL,
    "product_id"  serial references  products(id) NOT NULL,
    "energy_100g" character varying,
    "energy_from_fat_100g" character varying,
    "fat_100g" character varying,
    "saturated_fat_100g" character varying,
    "butyric_acid_100g" character varying,
    "caproic_acid_100g" character varying,
    "caprylic_acid_100g" character varying,
    "capric_acid_100g" character varying,
    "lauric_acid_100g" character varying,
    "myristic_acid_100g" character varying,
    "palmitic_acid_100g" character varying,
    "stearic_acid_100g" character varying,
    "arachidic_acid_100g" character varying,
    "behenic_acid_100g" character varying,
    "lignoceric_acid_100g" character varying,
    "cerotic_acid_100g" character varying,
    "montanic_acid_100g" character varying,
    "melissic_acid_100g" character varying,
    "monounsaturated_fat_100g" character varying,
    "polyunsaturated_fat_100g" character varying,
    "omega_3_fat_100g" character varying,
    "alpha_linolenic_acid_100g" character varying,
    "eicosapentaenoic_acid_100g" character varying,
    "docosahexaenoic_acid_100g" character varying,
    "omega_6_fat_100g" character varying,
    "linoleic_acid_100g" character varying,
    "arachidonic_acid_100g" character varying,
    "gamma_linolenic_acid_100g" character varying,
    "dihomo_gamma_linolenic_acid_100g" character varying,
    "omega_9_fat_100g" character varying,
    "oleic_acid_100g" character varying,
    "elaidic_acid_100g" character varying,
    "gondoic_acid_100g" character varying,
    "mead_acid_100g" character varying,
    "erucic_acid_100g" character varying,
    "nervonic_acid_100g" character varying,
    "trans_fat_100g" character varying,
    "cholesterol_100g" character varying,
    "carbohydrates_100g" character varying,
    "sugars_100g" character varying,
    "sucrose_100g" character varying,
    "glucose_100g" character varying,
    "fructose_100g" character varying,
    "lactose_100g" character varying,
    "maltose_100g" character varying,
    "maltodextrins_100g" character varying,
    "starch_100g" character varying,
    "polyols_100g" character varying,
    "fiber_100g" character varying,
    "proteins_100g" character varying,
    "casein_100g" character varying,
    "serum_proteins_100g" character varying,
    "nucleotides_100g" character varying,
    "salt_100g" character varying,
    "sodium_100g" character varying,
    "alcohol_100g" character varying,
    "vitamin_a_100g" character varying,
    "beta_carotene_100g" character varying,
    "vitamin_d_100g" character varying,
    "vitamin_e_100g" character varying,
    "vitamin_k_100g" character varying,
    "vitamin_c_100g" character varying,
    "vitamin_b1_100g" character varying,
    "vitamin_b2_100g" character varying,
    "vitamin_pp_100g" character varying,
    "vitamin_b6_100g" character varying,
    "vitamin_b9_100g" character varying,
    "folates_100g" character varying,
    "vitamin_b12_100g" character varying,
    "biotin_100g" character varying,
    "pantothenic_acid_100g" character varying,
    "silica_100g" character varying,
    "bicarbonate_100g" character varying,
    "potassium_100g" character varying,
    "chloride_100g" character varying,
    "calcium_100g" character varying,
    "phosphorus_100g" character varying,
    "iron_100g" character varying,
    "magnesium_100g" character varying,
    "zinc_100g" character varying,
    "copper_100g" character varying,
    "manganese_100g" character varying,
    "fluoride_100g" character varying,
    "selenium_100g" character varying,
    "chromium_100g" character varying,
    "molybdenum_100g" character varying,
    "iodine_100g" character varying,
    "caffeine_100g" character varying,
    "taurine_100g" character varying,
    "ph_100g" character varying,
    "fruits_vegetables_nuts_100g" character varying,
    "fruits_vegetables_nuts_dried_100g" character varying,
    "fruits_vegetables_nuts_estimate_100g" character varying,
    "collagen_meat_protein_ratio_100g" character varying,
    "cocoa_100g" character varying,
    "chlorophyl_100g" character varying,
    "carbon_footprint_100g" character varying,
    "carbon_footprint_from_meat_or_fish_100g" character varying,
    "nutrition_score_fr_100g" character varying,
    "nutrition_score_uk_100g" character varying,
    "glycemic_index_100g" character varying,
    "water_hardness_100g" character varying,
    "choline_100g" character varying,
    "phylloquinone_100g" character varying,
    "beta_glucan_100g" character varying,
    "inositol_100g" character varying,
    "carnitine_100g" character varying
  );`,
  },
];

// ---------------- Functions & script ----------------
const logger = (...args) => console.log(...args);

async function main() {
  const client = new Client(dbDns);

  await client
    .connect()
    .then(() => logger('[*] Connected to postgres client'))
    .catch((error) => {
      throw new Error(error);
    });

  await client
    .query(`DROP TABLE IF EXISTS products, product_nutrition_facts CASCADE;`)
    .then(() => logger(`[*] Dropped tables database`));

  for (let i = 0; i < tables.length; i++) {
    await client
      .query(tables[i].query)
      .then(() => logger(`[*] Created ${tables[i].table} schema`))
      .catch((error) => {
        throw new Error(error);
      });
  }

  csv(
    {
      output: 'json',
      maxRowLength: 65535,
      fork: true,
      delimiter: ',',
    },
    {},
  )
    .fromFile(csvFilePath)
    .subscribe(
      (doc, lineNumber) =>
        new Promise((resolve, reject) => {
          // console.log(doc.carbohydrates_100g);

          // return resolve();

          if (doc.product_name === '') {
            return reject();
          }

          logger(`Processing line ${lineNumber} --`, doc.product_name || null);

          return client
            .query(
              `INSERT INTO products(
                code,
                url,
                creator,
                created_t,
                created_datetime,
                last_modified_t,
                last_modified_datetime,
                product_name,
                generic_name,
                quantity,
                image_url,
                image_small_url
              ) VALUES(
                $1,
                $2,
                $3,
                $4,
                $5,
                $6,
                $7,
                $8,
                $9,
                $10,
                $11,
                $12
              ) RETURNING id`,
              [
                doc.code || null,
                doc.url || null,
                doc.creator || null,
                doc.created_t || null,
                doc.created_datetime || null,
                doc.last_modified_t || null,
                doc.last_modified_datetime || null,
                doc.product_name || null,
                doc.generic_name || null,
                doc.quantity || null,
                doc.image_url || null,
                doc.image_small_url || null,
              ],
            )
            .then((res) => {
              let productId = res.rows[0].id;

              client.query(
                `INSERT INTO product_nutrition_facts(
                  product_id,
                  energy_100g,
                  energy_from_fat_100g,
                  fat_100g,
                  saturated_fat_100g,
                  butyric_acid_100g,
                  caproic_acid_100g,
                  caprylic_acid_100g,
                  capric_acid_100g,
                  lauric_acid_100g,
                  myristic_acid_100g,
                  palmitic_acid_100g,
                  stearic_acid_100g,
                  arachidic_acid_100g,
                  behenic_acid_100g,
                  lignoceric_acid_100g,
                  cerotic_acid_100g,
                  montanic_acid_100g,
                  melissic_acid_100g,
                  monounsaturated_fat_100g,
                  polyunsaturated_fat_100g,
                  omega_3_fat_100g,
                  alpha_linolenic_acid_100g,
                  eicosapentaenoic_acid_100g,
                  docosahexaenoic_acid_100g,
                  omega_6_fat_100g,
                  linoleic_acid_100g,
                  arachidonic_acid_100g,
                  gamma_linolenic_acid_100g,
                  dihomo_gamma_linolenic_acid_100g,
                  omega_9_fat_100g,
                  oleic_acid_100g,
                  elaidic_acid_100g,
                  gondoic_acid_100g,
                  mead_acid_100g,
                  erucic_acid_100g,
                  nervonic_acid_100g,
                  trans_fat_100g,
                  cholesterol_100g,
                  carbohydrates_100g,
                  sugars_100g,
                  sucrose_100g,
                  glucose_100g,
                  fructose_100g,
                  lactose_100g,
                  maltose_100g,
                  maltodextrins_100g,
                  starch_100g,
                  polyols_100g,
                  fiber_100g,
                  proteins_100g,
                  casein_100g,
                  serum_proteins_100g,
                  nucleotides_100g,
                  salt_100g,
                  sodium_100g,
                  alcohol_100g,
                  vitamin_a_100g,
                  beta_carotene_100g,
                  vitamin_d_100g,
                  vitamin_e_100g,
                  vitamin_k_100g,
                  vitamin_c_100g,
                  vitamin_b1_100g,
                  vitamin_b2_100g,
                  vitamin_pp_100g,
                  vitamin_b6_100g,
                  vitamin_b9_100g,
                  folates_100g,
                  vitamin_b12_100g,
                  biotin_100g,
                  pantothenic_acid_100g,
                  silica_100g,
                  bicarbonate_100g,
                  potassium_100g,
                  chloride_100g,
                  calcium_100g,
                  phosphorus_100g,
                  iron_100g,
                  magnesium_100g,
                  zinc_100g,
                  copper_100g,
                  manganese_100g,
                  fluoride_100g,
                  selenium_100g,
                  chromium_100g,
                  molybdenum_100g,
                  iodine_100g,
                  caffeine_100g,
                  taurine_100g,
                  ph_100g,
                  fruits_vegetables_nuts_100g,
                  fruits_vegetables_nuts_dried_100g,
                  fruits_vegetables_nuts_estimate_100g,
                  collagen_meat_protein_ratio_100g,
                  cocoa_100g,
                  chlorophyl_100g,
                  carbon_footprint_100g,
                  carbon_footprint_from_meat_or_fish_100g,
                  nutrition_score_fr_100g,
                  nutrition_score_uk_100g,
                  glycemic_index_100g,
                  water_hardness_100g,
                  choline_100g,
                  phylloquinone_100g,
                  beta_glucan_100g,
                  inositol_100g,
                  carnitine_100g
              ) VALUES(
                $1,
                $2,
                $3,
                $4,
                $5,
                $6,
                $7,
                $8,
                $9,
                $10,
                $11,
                $12,
                $13,
                $14,
                $15,
                $16,
                $17,
                $18,
                $19,
                $20,
                $21,
                $22,
                $23,
                $24,
                $25,
                $26,
                $27,
                $28,
                $29,
                $30,
                $31,
                $32,
                $33,
                $34,
                $35,
                $36,
                $37,
                $38,
                $39,
                $40,
                $41,
                $42,
                $43,
                $44,
                $45,
                $46,
                $47,
                $48,
                $49,
                $50,
                $51,
                $52,
                $53,
                $54,
                $55,
                $56,
                $57,
                $58,
                $59,
                $60,
                $61,
                $62,
                $63,
                $64,
                $65,
                $66,
                $67,
                $68,
                $69,
                $70,
                $71,
                $72,
                $73,
                $74,
                $75,
                $76,
                $77,
                $78,
                $79,
                $80,
                $81,
                $82,
                $83,
                $84,
                $85,
                $86,
                $87,
                $88,
                $89,
                $90,
                $91,
                $92,
                $93,
                $94,
                $95,
                $96,
                $97,
                $98,
                $99,
                $100,
                $101,
                $102,
                $103,
                $104,
                $105,
                $106,
                $107,
                $108
              )`,
                [
                  productId,
                  doc.energy_100g,
                  doc.energy_from_fat_100g,
                  doc.fat_100g,
                  doc.saturated_fat_100g,
                  doc.butyric_acid_100g,
                  doc.caproic_acid_100g,
                  doc.caprylic_acid_100g,
                  doc.capric_acid_100g,
                  doc.lauric_acid_100g,
                  doc.myristic_acid_100g,
                  doc.palmitic_acid_100g,
                  doc.stearic_acid_100g,
                  doc.arachidic_acid_100g,
                  doc.behenic_acid_100g,
                  doc.lignoceric_acid_100g,
                  doc.cerotic_acid_100g,
                  doc.montanic_acid_100g,
                  doc.melissic_acid_100g,
                  doc.monounsaturated_fat_100g,
                  doc.polyunsaturated_fat_100g,
                  doc.omega_3_fat_100g,
                  doc.alpha_linolenic_acid_100g,
                  doc.eicosapentaenoic_acid_100g,
                  doc.docosahexaenoic_acid_100g,
                  doc.omega_6_fat_100g,
                  doc.linoleic_acid_100g,
                  doc.arachidonic_acid_100g,
                  doc.gamma_linolenic_acid_100g,
                  doc.dihomo_gamma_linolenic_acid_100g,
                  doc.omega_9_fat_100g,
                  doc.oleic_acid_100g,
                  doc.elaidic_acid_100g,
                  doc.gondoic_acid_100g,
                  doc.mead_acid_100g,
                  doc.erucic_acid_100g,
                  doc.nervonic_acid_100g,
                  doc.trans_fat_100g,
                  doc.cholesterol_100g,
                  doc.carbohydrates_100g,
                  doc.sugars_100g,
                  doc.sucrose_100g,
                  doc.glucose_100g,
                  doc.fructose_100g,
                  doc.lactose_100g,
                  doc.maltose_100g,
                  doc.maltodextrins_100g,
                  doc.starch_100g,
                  doc.polyols_100g,
                  doc.fiber_100g,
                  doc.proteins_100g,
                  doc.casein_100g,
                  doc.serum_proteins_100g,
                  doc.nucleotides_100g,
                  doc.salt_100g,
                  doc.sodium_100g,
                  doc.alcohol_100g,
                  doc.vitamin_a_100g,
                  doc.beta_carotene_100g,
                  doc.vitamin_d_100g,
                  doc.vitamin_e_100g,
                  doc.vitamin_k_100g,
                  doc.vitamin_c_100g,
                  doc.vitamin_b1_100g,
                  doc.vitamin_b2_100g,
                  doc.vitamin_pp_100g,
                  doc.vitamin_b6_100g,
                  doc.vitamin_b9_100g,
                  doc.folates_100g,
                  doc.vitamin_b12_100g,
                  doc.biotin_100g,
                  doc.pantothenic_acid_100g,
                  doc.silica_100g,
                  doc.bicarbonate_100g,
                  doc.potassium_100g,
                  doc.chloride_100g,
                  doc.calcium_100g,
                  doc.phosphorus_100g,
                  doc.iron_100g,
                  doc.magnesium_100g,
                  doc.zinc_100g,
                  doc.copper_100g,
                  doc.manganese_100g,
                  doc.fluoride_100g,
                  doc.selenium_100g,
                  doc.chromium_100g,
                  doc.molybdenum_100g,
                  doc.iodine_100g,
                  doc.caffeine_100g,
                  doc.taurine_100g,
                  doc.ph_100g,
                  doc.fruits_vegetables_nuts_100g,
                  doc.fruits_vegetables_nuts_dried_100g,
                  doc.fruits_vegetables_nuts_estimate_100g,
                  doc.collagen_meat_protein_ratio_100g,
                  doc.cocoa_100g,
                  doc.chlorophyl_100g,
                  doc.carbon_footprint_100g,
                  doc.carbon_footprint_from_meat_or_fish_100g,
                  doc.nutrition_score_fr_100g,
                  doc.nutrition_score_uk_100g,
                  doc.glycemic_index_100g,
                  doc.water_hardness_100g,
                  doc.choline_100g,
                  doc.phylloquinone_100g,
                  doc.beta_glucan_100g,
                  doc.inositol_100g,
                  doc.carnitine_100g,
                ],
              );
            })
            .then(resolve)
            .catch((error) => reject(error));
        }),
      (error) => {
        throw new Error(error);
      },
      () => {
        logger('Done.');
        client.end();
        process.exit();
      },
    );
}

main();
